// MIT License

// Copyright (c) 2026 The orion Developers

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

//! Hybrid Public Key Encryption.
//!
//! # Use case:
//! `orion::hpke` can be used to encrypt one or more messages for a recipient public key.
//!
//! # About:
//! - Uses the PQ/T HPKE suite `X-Wing/(ML-KEM768, X25519), SHAKE256, ChaCha20Poly1305`.
//! - HPKE provides no forward secrecy for the recipient long-term key. If the recipients long-term
//!   key is compromised, past ciphertext can be decrypted.
//! - Messages muist be decrypted in the same order they were encrypted.
//!   HPKE provides no further protections against replay.
//! - Length of the messages encrypted are not hidden.
//! - Base-mode provides no sender authentication. PSK-mode should be used for this.
//!
//! Please refer to the [RFC9180] for more security information.
//!
//! This suite is defined in:
//! - KEM suite: [draft-irtf-cfrg-concrete-hybrid-kems-04](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-concrete-hybrid-kems-04)
//! - HPKE suite: [draft-ietf-hpke-pq-05](https://datatracker.ietf.org/doc/html/draft-ietf-hpke-pq-05)
//!
//! # Parameters:
//! - `pubkey_r`: Public key of the recipient.
//! - `info`: Optional additional information for HPKE state. Must be identical for sender and recipient.
//! - `enc`: Encapsulated key, generated by the sender.
//! - `secret_key_r`: Secret key of the recipient.
//! - `exporter_context`: Contextual information used during secret export.
//! - `psk`: Pre-shared key known to both sender and recipient.
//! - `psk_id`: The identifier for `psk`.
//! - `secret_ephemeral`: Ephemeral private key for deterministic encapsulation.
//!
//! # Errors:
//! An error will be returned if:
//! - `info` is longer than `64` bytes
//! - `out` buffer is longer than [`EXPORT_SECRET_MAXLEN`] when exporting secrets with [`HpkeBase::export_secret()`]/[`HpkePsk::export_secret()`]
//! - `exporter_context` is longer than `64` bytes
//! - The internal counter reaches [`u64::MAX`] and a call to `seal()`]/`open()` is made
//! - Calling [`HpkeBase::seal()`]/[`HpkePsk::seal()`] when the role is recipient
//! - Calling [`HpkeBase::open()`]/[`HpkePsk::open()`] when the role is sender
//! - Calling [`HpkeBase::open()`]/[`HpkePsk::open()`] on a set of messages that does not match the order of how they were `seal()`'ed (re-ordering)
//! - `psk` or `psk_id` are empty
//! - `psk` is less than `32` bytes or more than `64` bytes
//! - `psk_id` is more than `64` bytes
//! - If a shared secret is all-zero.
//! - If `ikm.len() < 32` when calling `derive_keypair()` on a suite's KEM.
//! - `getrandom` errors during [`HpkeBase::new_sender()`]/[`HpkePsk::new_sender()`] or [`HpkePsk::seal()`].
//!
//! # Security:
//! - If forward secrecy for both the recipient and receiver are required, what is usaully considered the long-term
//!   key in HPKE, should be made ephemeral (generated for each message). This turn it into an interactive protocol
//!   and is nont specified in the standard. Frequent key-rotations of "long-term" keys will shrink the window of
//!   compromised ciphertexts, for a single key, if leaked.
//! - The `ikm` used as input for `derive_keypair()` must never be reused.
//! - The `secret_ephemeral` must never be reused.
//!
//! # Example:
//! ```rust
//! use orion::hpke::*;
//!
//! let sender_kp = KeyPair::generate()?;
//! let recipient_kp = KeyPair::generate()?;
//! let psk = b"any preshared secret key that is 32 bytes minimum";
//! let psk_id = b"identifier for psk";
//!
//! // Streaming-based API
//! let mut aead_ct_out0 = [0u8; 32];
//! let mut aead_ct_out1 = [0u8; 32];
//! let mut aead_ct_out2 = [0u8; 32];
//!
//! let (mut hpke_sender, enc) = HpkeBase::new_sender(recipient_kp.public(), b"info parameter")?;
//! hpke_sender.seal(&[0u8; 16], b"aad parameter 0", &mut aead_ct_out0)?;
//! hpke_sender.seal(&[1u8; 16], b"aad parameter 1", &mut aead_ct_out1)?;
//! hpke_sender.seal(&[2u8; 16], b"aad parameter 2", &mut aead_ct_out2)?;
//!
//! let mut hpke_recipient = HpkeBase::new_recipient(&enc, recipient_kp.private(), b"info parameter")?;
//! let mut aead_pt_out0 = [0u8; 16];
//! let mut aead_pt_out1 = [0u8; 16];
//! let mut aead_pt_out2 = [0u8; 16];
//! hpke_recipient.open(&aead_ct_out0, b"aad parameter 0", &mut aead_pt_out0)?;
//! hpke_recipient.open(&aead_ct_out1, b"aad parameter 1", &mut aead_pt_out1)?;
//! hpke_recipient.open(&aead_ct_out2, b"aad parameter 2", &mut aead_pt_out2)?;
//!
//! assert_eq!(&aead_pt_out0, &[0u8; 16]);
//! assert_eq!(&aead_pt_out1, &[1u8; 16]);
//! assert_eq!(&aead_pt_out2, &[2u8; 16]);
//!
//! // One-shot API
//! let enc = HpkePsk::psk_seal(recipient_kp.public(), b"info parameter", psk, psk_id, &[3u8; 16], b"aad", &mut aead_ct_out0)?;
//! HpkePsk::psk_open(&enc, recipient_kp.private(), b"info parameter", psk, psk_id, &aead_ct_out0, b"aad", &mut aead_pt_out0)?;
//! assert_eq!(&aead_pt_out0, &[3u8; 16]);
//! # Ok::<(), orion::errors::UnknownCryptoError>(())
//! ```
//! [RFC9180]: <https://www.rfc-editor.org/rfc/rfc9180.html#name-security-considerations>
//! [`xwing::DecapsulationKey`]: crate::hazardous::kem::xwing::DecapsulationKey

#![cfg_attr(docsrs, doc(cfg(feature = "safe_api")))]

pub use crate::KP;
pub use crate::hazardous::hpke::MLKEM768_X25519_SHAKE256_CHACHA20;
pub use crate::hazardous::hpke::ModeBase;
pub use crate::hazardous::hpke::ModePsk;
pub use crate::hazardous::kem::xwing::KeyPair;

/// Maximum secret export length.
pub const EXPORT_SECRET_MAXLEN: usize = MLKEM768_X25519_SHAKE256_CHACHA20::EXPORT_SECRET_MAXLEN;

/// PQ/T HPKE with X-Wing and SHAKE256 in base-mode.
pub type HpkeBase = ModeBase<MLKEM768_X25519_SHAKE256_CHACHA20>;

/// PQ/T HPKE with X-Wing and SHAKE256 in PSK-mode.
pub type HpkePsk = ModePsk<MLKEM768_X25519_SHAKE256_CHACHA20>;
