name: cargo deny (licenses, advisories, sources)

permissions:
  contents: read

on:
  push:
    # Check immediately if dependencies are altered
    paths:
      - "**/Cargo.toml"
    # Check also at midnight each day
  schedule:
    - cron: "0 0 * * *"

# We don't need to run older workflows for the same PR's, since we always want the output of the newest ones.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cargo-deny:
    name: EmbarkStudios/cargo-deny
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: EmbarkStudios/cargo-deny-action@bb137d7af7e4fb67e5f82a49c4fce4fad40782fe # v2.0.20
        with:
          command: check ${{ matrix.checks }}
