name: cargo deny (licenses, advisories, sources)

permissions:
  contents: read

on:
  push:
    # Check immediately if dependencies are altered
    paths:
      - "**/Cargo.toml"
    # Check also at midnight each day
  schedule:
    - cron: "0 0 * * *"

# We don't need to run older workflows for the same PR's, since we always want the output of the newest ones.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cargo-deny:
    name: EmbarkStudios/cargo-deny
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: EmbarkStudios/cargo-deny-action@3c6349835b2b7b196a839186cb8b78e02f7b5f25 # v2.1.1
        with:
          command: check ${{ matrix.checks }}
